// Copyright 2026 Greg Van Horn and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type CatalogSearchFacetsItem struct {
	Name  string `json:"name"`
	Total int    `json:"total"`
	Type  string `json:"type"`
}

type CatalogSearchItem struct {
	Name  string `json:"name"`
	Total int    `json:"total"`
	Type  string `json:"type"`
}

type dataset struct {
	Type               string          `json:"@type"`
	AccessLevel        string          `json:"accessLevel"`
	AccrualPeriodicity string          `json:"accrualPeriodicity"`
	BureauCode         json.RawMessage `json:"bureauCode"`
	ContactPoint       json.RawMessage `json:"contactPoint"`
	DescribedBy        string          `json:"describedBy"`
	DescribedByType    string          `json:"describedByType"`
	Description        string          `json:"description"`
	Distribution       json.RawMessage `json:"distribution"`
	Identifier         string          `json:"identifier"`
	IsPartOf           string          `json:"isPartOf"`
	Issued             string          `json:"issued"`
	Keyword            json.RawMessage `json:"keyword"`
	License            string          `json:"license"`
	Modified           string          `json:"modified"`
	ProgramCode        json.RawMessage `json:"programCode"`
	Publisher          json.RawMessage `json:"publisher"`
	References         json.RawMessage `json:"references"`
	Spatial            string          `json:"spatial"`
	Temporal           string          `json:"temporal"`
	Theme              json.RawMessage `json:"theme"`
	Title              string          `json:"title"`
}

type datastoreQuery struct {
	Conditions json.RawMessage `json:"conditions"`
	Count      bool            `json:"count"`
	Format     string          `json:"format"`
	Groupings  json.RawMessage `json:"groupings"`
	Joins      json.RawMessage `json:"joins"`
	Keys       bool            `json:"keys"`
	Limit      int             `json:"limit"`
	Offset     int             `json:"offset"`
	Properties json.RawMessage `json:"properties"`
	Resources  json.RawMessage `json:"resources"`
	Results    bool            `json:"results"`
	RowIds     bool            `json:"rowIds"`
	Schema     bool            `json:"schema"`
	Sorts      json.RawMessage `json:"sorts"`
}

type datastoreQueryCondition struct {
	Operator string `json:"operator"`
	Property string `json:"property"`
	Resource string `json:"resource"`
	Value    string `json:"value"`
}

type datastoreQueryConditionGroup struct {
	Conditions    json.RawMessage `json:"conditions"`
	GroupOperator string          `json:"groupOperator"`
}

type datastoreQueryExpression struct {
	Operands json.RawMessage `json:"operands"`
	Operator string          `json:"operator"`
}

type datastoreQueryResourceProperty struct {
	Property string `json:"property"`
	Resource string `json:"resource"`
}

type datastoreQuerySort struct {
	Order    string `json:"order"`
	Property string `json:"property"`
	Resource string `json:"resource"`
}

type datastoreResourceQuery struct {
	Conditions json.RawMessage `json:"conditions"`
	Count      bool            `json:"count"`
	Format     string          `json:"format"`
	Groupings  json.RawMessage `json:"groupings"`
	Keys       bool            `json:"keys"`
	Limit      int             `json:"limit"`
	Offset     int             `json:"offset"`
	Properties json.RawMessage `json:"properties"`
	Results    bool            `json:"results"`
	RowIds     bool            `json:"rowIds"`
	Schema     bool            `json:"schema"`
	Sorts      json.RawMessage `json:"sorts"`
}

type errorResponse struct {
	Data      json.RawMessage `json:"data"`
	Message   string          `json:"message"`
	Status    int             `json:"status"`
	Timestamp string          `json:"timestamp"`
}

type harvestPlan struct {
	Extract    json.RawMessage `json:"extract"`
	Identifier string          `json:"identifier"`
	Load       json.RawMessage `json:"load"`
}

type metastoreNewRevision struct {
	Message string `json:"message"`
	State   string `json:"state"`
}

type metastoreRevision struct {
	Identifier string `json:"identifier"`
	Message    string `json:"message"`
	Modified   string `json:"modified"`
	Published  bool   `json:"published"`
	State      string `json:"state"`
}

type metastoreWriteResponse struct {
	Endpoint   string `json:"endpoint"`
	Identifier string `json:"identifier"`
}
