// Copyright 2026 Claude and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCatalogCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "catalog",
		Short:       "Manage catalog command groups",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCatalogSearchCmd(flags))
	cmd.AddCommand(newCatalogSearchFacetsCmd(flags))
	return cmd
}
