// Copyright 2026 Greg Van Horn and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newDatastoreResourceQueryGetCmd(flags *rootFlags) *cobra.Command {
	var flagLimit int
	var flagOffset string
	var flagCount bool
	var flagResults bool
	var flagSchema bool
	var flagKeys bool
	var flagFormat string
	var flagRowIds bool
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "resource-query-get <distributionId>",
		Short:       "Simple GET equivalent of a POST query.",
		Example:     "  openpayments-pp-cli datastore resource-query-get 004e1f11-aa67-5b16-943d-1fe1044b3512",
		Annotations: map[string]string{"pp:endpoint": "datastore.resource-query-get", "pp:method": "GET", "pp:path": "/api/1/datastore/query/{distributionId}", "mcp:read-only": "true", "pp:happy-args": "distributionId=004e1f11-aa67-5b16-943d-1fe1044b3512"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <distributionId>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <distributionId>"))
			}
			if cmd.Flags().Changed("format") {
				allowedFormat := []string{"csv", "json"}
				validFormat := false
				for _, v := range allowedFormat {
					if flagFormat == v {
						validFormat = true
						break
					}
				}
				if !validFormat {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagFormat, "format", allowedFormat)
				}
			}
			path := "/api/1/datastore/query/{distributionId}"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("distributionId is required\nUsage: %s <%s>", cmd.CommandPath(), "distributionId"))
			}
			path = replacePathParam(path, "distributionId", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "datastore", path, retainCLIQueryParams(cmd, map[string]string{
				"limit":   formatCLIParamValue(flagLimit),
				"offset":  formatCLIParamValue(flagOffset),
				"count":   formatCLIParamValue(flagCount),
				"results": formatCLIParamValue(flagResults),
				"schema":  formatCLIParamValue(flagSchema),
				"keys":    formatCLIParamValue(flagKeys),
				"format":  formatCLIParamValue(flagFormat),
				"rowIds":  formatCLIParamValue(flagRowIds),
			}, map[string][]string{"limit": {"limit"}, "offset": {"offset"}, "count": {"count"}, "results": {"results"}, "schema": {"schema"}, "keys": {"keys"}, "format": {"format"}, "rowIds": {"row-ids"}}, "offset", "offset"), nil, flagAll, "offset", "offset", "limit", 0, "", "", "results", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := collectionItemsForOutput(data, path)
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(outputData, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				var selectErr error
				filtered := data
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
					selectErr = selectErrorForDryRun(selectErr, flags, data)
				} else if flags.compact {
					filtered = compactFields(filtered, nil)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				if err := printOutput(cmd.OutOrStdout(), wrapped, true); err != nil {
					return err
				}
				return selectErr
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, nil)
		},
	}
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Limit")
	cmd.Flags().StringVar(&flagOffset, "offset", "0", "Offset")
	cmd.Flags().BoolVar(&flagCount, "count", true, "Count")
	cmd.Flags().BoolVar(&flagResults, "results", true, "Results")
	cmd.Flags().BoolVar(&flagSchema, "schema", true, "Schema")
	cmd.Flags().BoolVar(&flagKeys, "keys", true, "Keys")
	cmd.Flags().StringVar(&flagFormat, "format", "json", "Format (one of: csv, json)")
	cmd.Flags().BoolVar(&flagRowIds, "row-ids", false, "Row ids")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
