// Copyright 2026 Greg Van Horn and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMetastoreCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "metastore",
		Short:       "Work with metadata items.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMetastoreDatasetGetItemCmd(flags))
	cmd.AddCommand(newMetastoreGetAllCmd(flags))
	cmd.AddCommand(newMetastoreGetSchemaCmd(flags))
	cmd.AddCommand(newMetastoreGetSchemasCmd(flags))
	return cmd
}
